# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: go-crossbuild
      # You may pin to the exact commit or the version.
      # uses: izumin5210/action-go-crossbuild@77788a44756d2fd2ba1eb9a4252b471397c63ffc
      uses: izumin5210/action-go-crossbuild@v1.0.0
      with:
        # An application name
        #name: # optional, default is 
        # Space or comma separated list of GOARCH
        arch: amd64,arm64
        # Path to destination directory of built binaries
        #dest: # optional, default is ./dist
        # `-ldflags` to pass to go build
        #ldflags: # optional, default is 
        # `-tags` to pass to go build
        #tags: # optional, default is 
        # Space or comma separated list of GOOS
        os: linux,windows
        # Build target package
        #package: # optional, default is .
        # Version of github.com/Songmu/goxz
        #goxz-version: # optional, default is v0.4.1
            
